version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-juntas
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=juntas-app

volumes:
  mongodb_data: