# fly.toml app configuration file generated for juntas-seguras on 2023-09-22T14:24:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "juntas-seguras"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
